### ISSUE TITLE
Broken import of MultitaskDataset

### ISSUE THREAD

**Issue by Peter-Devine** [HazyResearch/snorkel-superglue#22]
In every task parser, as well as in utils.py, the following is imported:
```
from snorkel.mtl.data import MultitaskDataset
```
However, the current Snorkel installation does not have an `mtl` folder, so this import fails. Is this present in a previous version of Snorkel?

Thanks

**Comment by honorinli151** [comment]
The Snorkel repo has a superglue tag.
OR you could just pip install the requierment.txt in this repo.
